import "dotenv/config"

const DEP_URL = "https://raw.githubusercontent.com/RitchieRD/ubigeos-peru-data/main/json/1_ubigeo_departamentos.json"
const PROV_URL = "https://raw.githubusercontent.com/RitchieRD/ubigeos-peru-data/main/json/2_ubigeo_provincias.json"
const DIST_URL = "https://raw.githubusercontent.com/RitchieRD/ubigeos-peru-data/main/json/3_ubigeo_distritos.json"

interface DeptJson {
  id: number
  departamento: string
  ubigeo: string
}

interface ProvJson {
  id: number
  provincia: string
  ubigeo: string
  departamento_id: number
}

interface DistJson {
  id: number
  distrito: string
  ubigeo: string
  provincia_id: number
  departamento_id: number
}

function normalizeKey(s: string): string {
  return s.toLowerCase()
    .normalize("NFD").replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]/g, "")
}

function titleCase(s: string): string {
  const lower = s.toLowerCase()
  const words = lower.split(" ")
  const lowExceptions = ["de", "del", "y", "e", "la", "las", "los", "el", "en", "un", "una", "con"]
  return words.map((w, i) => {
    if (i > 0 && lowExceptions.includes(w)) return w
    return w.charAt(0).toUpperCase() + w.slice(1)
  }).join(" ")
}

async function main() {
  console.log("Fetching departments...")
  const depsRaw: { ubigeo_departamentos: DeptJson[] } = await fetch(DEP_URL).then(r => r.json())
  console.log("Fetching provinces...")
  const provsRaw: { ubigeo_provincias: ProvJson[] } = await fetch(PROV_URL).then(r => r.json())
  console.log("Fetching districts...")
  const distsRaw: { ubigeo_distritos: DistJson[] } = await fetch(DIST_URL).then(r => r.json())

  const deps = depsRaw.ubigeo_departamentos
  const provs = provsRaw.ubigeo_provincias
  const dists = distsRaw.ubigeo_distritos

  // Build department map: normalizeKey -> { id, titleCased }
  const deptMap = new Map<string, { id: number; name: string }>()
  for (const d of deps) {
    const tc = titleCase(d.departamento)
    const key = normalizeKey(tc)
    // Fix known accent mismatches for departments
    const fixed = fixKnownAccents(tc)
    deptMap.set(key, { id: d.id, name: fixed })
  }

  // Build province maps: by id -> name, and by dept id -> map of prov id -> name
  const provById = new Map<number, string>()
  const provByDept = new Map<number, Map<number, string>>()
  for (const p of provs) {
    const tc = fixKnownAccents(titleCase(p.provincia))
    provById.set(p.id, tc)
    if (!provByDept.has(p.departamento_id)) {
      provByDept.set(p.departamento_id, new Map())
    }
    provByDept.get(p.departamento_id)!.set(p.id, tc)
  }

  // Build districts structure: deptName -> { provName -> dist[] }
  const result: Record<string, Record<string, string[]>> = {}

  for (const dist of dists) {
    const deptEntry = [...deptMap.values()].find(d => d.id === dist.departamento_id)
    if (!deptEntry) continue

    const deptName = deptEntry.name
    const provInner = provByDept.get(dist.departamento_id)
    if (!provInner) continue

    const provName = provInner.get(dist.provincia_id)
    if (!provName) continue

    if (!result[deptName]) result[deptName] = {}
    if (!result[deptName][provName]) result[deptName][provName] = []

    const districtName = fixKnownAccents(titleCase(dist.distrito))
    result[deptName][provName].push(districtName)
  }

  // Sort districts within each province
  for (const dept of Object.keys(result)) {
    for (const prov of Object.keys(result[dept])) {
      result[dept][prov].sort()
    }
  }

  // Generate TypeScript
  let output = `// Auto-generated by scripts/build-districts.ts\n`
  output += `// Do not edit manually\n`
  output += `export const peruDistricts: Record<string, Record<string, string[]>> = ${JSON.stringify(result, null, 2)}\n`

  // Write to lib/peru-data.ts by appending after the last line
  const fs = await import("fs/promises")
  const existing = await fs.readFile("lib/peru-data.ts", "utf-8")
  // Check if peruDistricts already exists
  if (existing.includes("export const peruDistricts")) {
    console.log("peruDistricts already exists in lib/peru-data.ts, replacing...")
    const idx = existing.indexOf("export const peruDistricts")
    const newContent = existing.substring(0, idx) + output
    await fs.writeFile("lib/peru-data.ts", newContent, "utf-8")
  } else {
    await fs.appendFile("lib/peru-data.ts", "\n\n" + output, "utf-8")
  }

  // Count
  let distCount = 0
  let provCount = 0
  for (const dept of Object.keys(result)) {
    for (const prov of Object.keys(result[dept])) {
      provCount++
      distCount += result[dept][prov].length
    }
  }
  console.log(`✅ Generated: ${Object.keys(result).length} departments, ${provCount} provinces, ${distCount} districts`)
}

const accentFixes: Record<string, string> = {
  "Ancash": "Áncash",
  "Apurimac": "Apurímac",
  "Huanuco": "Huánuco",
  "Junin": "Junín",
  "San Martin": "San Martín",
  "Azangaro": "Azángaro",
  "Bolivar": "Bolívar",
  "Bongara": "Bongará",
  "Camana": "Camaná",
  "Canas": "Cañas",
  "Canete": "Cañete",
  "Caraveli": "Caravelí",
  "Celendin": "Celendín",
  "Chepen": "Chepén",
  "Concepcion": "Concepción",
  "Contumaza": "Contumazá",
  "Datem Del Maranon": "Datem del Marañón",
  "Gran Chimu": "Gran Chimú",
  "Huamalies": "Huamalíes",
  "Huancane": "Huancané",
  "Huarochiri": "Huarochirí",
  "Jaen": "Jaén",
  "Julcan": "Julcán",
  "La Convencion": "La Convención",
  "La Union": "La Unión",
  "Llamellin": "Llamellín",
  "Maranon": "Marañón",
  "Morropon": "Morropón",
  "Oyon": "Oyón",
  "Paucar Del Sara Sara": "Paúcar del Sara Sara",
  "Purus": "Purús",
  "Rodriguez De Mendoza": "Rodríguez de Mendoza",
  "San Roman": "San Román",
  "Sanchez Carrion": "Sánchez Carrión",
  "Sandia": "Sandía",
  "Santiago De Chuco": "Santiago de Chuco",
  "Victor Fajardo": "Víctor Fajardo",
  "Vilcas Huaman": "Vilcas Huamán",
  "Viru": "Virú",
  "Mariscal Caceres": "Mariscal Cáceres",
  "Daniel Alcides Carrion": "Daniel Alcides Carrión",
  "General Sanchez Cerro": "General Sánchez Cerro",
  "San Antonio De Putina": "San Antonio de Putina",
}

function fixKnownAccents(name: string): string {
  return accentFixes[name] || name
}

main().catch(console.error)
